{{- if and .Values.database.createSecret .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
type: Opaque
stringData:
  password: {{ .Values.database.password | quote }}
{{- end }}

