{{- if .Values.autoscaling.enabled }}
{{- range $name, $svc := .Values.services }}
{{- if ne (default "deployment" $svc.workload) "deployment" }}
{{- continue }}
{{- end }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ecommerce-platform.fullname" $ }}-{{ $name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ecommerce-platform.fullname" $ }}-{{ $name }}
  minReplicas: {{ $.Values.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.autoscaling.targetCPU }}
    {{- if $.Values.autoscaling.throttling.enabled }}
    - type: Pods
      pods:
        metric:
          name: {{ $.Values.autoscaling.throttling.metricName }}
        target:
          type: AverageValue
          averageValue: {{ $.Values.autoscaling.throttling.targetAverageValue | quote }}
    {{- end }}
---
{{- end }}
{{- end }}

