{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecommerce-platform.serviceAccountName" . }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- range $k, $v := .Values.serviceAccount.annotations }}
    {{ $k }}: "{{ $v }}"
    {{- end }}
  {{- end }}
{{- end }}

