{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-platform.fullname" $ }}-{{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ $svc.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $name }}
---
{{- end }}

