{{- if .Values.monitoring.enabled }}
{{- range $name, $svc := .Values.services }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ecommerce-platform.fullname" $ }}-{{ $name }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $.Values.monitoring.scrapeInterval }}
{{- end }}
{{- end }}

